/**
 * Generates apps/desktop/src/core-version.ts with the core version (root
 * package.json) that the app bundles as its offline sidecar fallback. Run as the
 * first step of `build:main` so the constant is always current. The generated
 * file is gitignored — it is a build artifact, not source.
 */
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); // apps/desktop/scripts
const repoRoot = join(here, "..", "..", "..");
const pkg = JSON.parse(await Bun.file(join(repoRoot, "package.json")).text()) as { version: string };

const out = join(here, "..", "src", "core-version.ts");
await Bun.write(
  out,
  `// GENERATED by scripts/gen-core-version.ts — do not edit.\n` +
    `// The core version embedded into this build as the offline sidecar fallback.\n` +
    `export const BUNDLED_CORE_VERSION = ${JSON.stringify(pkg.version)};\n`,
);

console.log(`▶ core-version.ts → BUNDLED_CORE_VERSION = ${pkg.version}`);
