export const SAMPLE_MARKDOWN = [
  "",
  "# Markdown Engine Spike",
  "",
  "Paragraph with inline code: ``const s = \"` * [x] https://example.com/zh?q=[a] 🚀\"`` plus **strong**, *emphasis*, [a link](https://example.com/docs?a=[b]), 中文, and emoji 😀.",
  "",
  "```ts",
  "const ticks = \"`inline` and ``double``\";",
  "const markdown = \"**bold** [link](https://example.com)\";",
  "console.log(ticks, markdown);",
  "```",
  "",
  "1. Ordered parent",
  "   1. Nested ordered child",
  "",
  "- Pure bullet parent",
  "  - Pure nested bullet",
  "",
  "- Parent item",
  "  - Nested child item",
  "  - ",
  "- [ ] Open task with `inline * code`",
  "  - [x] Nested done task",
  "- [ ] ",
  "",
  "> Blockquote with **strong text**",
  ">",
  "> - quoted list item",
  "",
  "## Secondary Heading",
  "",
  "---",
  "",
  "| Name | Value | Notes |",
  "| --- | --- | --- |",
  "| escaped pipe | a \\| b | keeps literal pipe |",
  "| url | https://example.com/a?x=1&y=2 | [inside link](https://example.com) |",
  "",
  "![Standalone image](https://placehold.co/640x240/png?text=Markdown+Image)",
  "",
  "[Standalone file link](./files/sample-report.pdf)",
  "",
  "```mh-html",
  "<section data-kind=\"callout\">",
  "  <strong>HTML block</strong>",
  "  <span>kept as markdown fence</span>",
  "</section>",
  "```",
  "",
  "",
  "Trailing paragraph after two blank lines.",
  "",
  "",
].join("\n");

export const MANUAL_CHECKLIST = [
  "Cross-block selection, copy, paste, undo, and redo keep Markdown intact.",
  "Dragging paragraph, list, code, table, image, and mh-html blocks does not corrupt Markdown ranges.",
  "Code fence arrow keys, Tab, mouse positioning, and fence exit behavior feel natural.",
  "Inline code with backticks, stars, brackets, URLs, Chinese text, and emoji survives edits.",
  "Nested list, task list, and empty list item Enter/Tab/Backspace behavior is acceptable.",
  "Pipe table with escaped \\| serializes without losing literal pipes.",
  "Standalone image and file links remain Markdown-only persisted data.",
  "mh-html fence survives Markdown -> editor -> Markdown without content loss.",
  "Repeated Markdown round trips do not keep drifting after normalization.",
  "IME Chinese composition is not interrupted by keymaps.",
];

export const REQUIRED_BLOCK_TYPES = [
  "heading",
  "paragraph",
  "list",
  "task",
  "code_fence",
  "quote",
  "table",
  "media",
  "divider",
  "html_fence",
] as const;

export type RequiredBlockType = (typeof REQUIRED_BLOCK_TYPES)[number];
